
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AMIGO BEBIDA CARNE COMIDA CONTRIBUI ENTRETENIMENTO IGUAL ITEM NUMERO PRECO_KG PRECO_L PRECO_UNIT QUANTIDADE QUANTIDADE_KG QUANTIDADE_L RATEIO STRING VEGETARIANOprogram : comandoscomandos : comandos comando\n                | comandocomando : AMIGO STRING CONTRIBUI NUMEROcomando : AMIGO STRING CONTRIBUI NUMERO VEGETARIANOcomando : ITEM CARNE STRING PRECO_KG NUMERO QUANTIDADE_KG NUMEROcomando : ITEM BEBIDA PRECO_L NUMERO QUANTIDADE_L NUMEROcomando : ITEM COMIDA PRECO_UNIT NUMERO QUANTIDADE NUMEROcomando : ITEM ENTRETENIMENTO PRECO_UNIT NUMERO QUANTIDADE NUMEROcomando : RATEIO IGUAL'
    
_lr_action_items = {'AMIGO':([0,2,3,7,13,19,24,30,31,32,33,],[4,4,-3,-2,-10,-4,-5,-7,-8,-9,-6,]),'ITEM':([0,2,3,7,13,19,24,30,31,32,33,],[5,5,-3,-2,-10,-4,-5,-7,-8,-9,-6,]),'RATEIO':([0,2,3,7,13,19,24,30,31,32,33,],[6,6,-3,-2,-10,-4,-5,-7,-8,-9,-6,]),'$end':([1,2,3,7,13,19,24,30,31,32,33,],[0,-1,-3,-2,-10,-4,-5,-7,-8,-9,-6,]),'STRING':([4,9,],[8,15,]),'CARNE':([5,],[9,]),'BEBIDA':([5,],[10,]),'COMIDA':([5,],[11,]),'ENTRETENIMENTO':([5,],[12,]),'IGUAL':([6,],[13,]),'CONTRIBUI':([8,],[14,]),'PRECO_L':([10,],[16,]),'PRECO_UNIT':([11,12,],[17,18,]),'NUMERO':([14,16,17,18,20,26,27,28,29,],[19,21,22,23,25,30,31,32,33,]),'PRECO_KG':([15,],[20,]),'VEGETARIANO':([19,],[24,]),'QUANTIDADE_L':([21,],[26,]),'QUANTIDADE':([22,23,],[27,28,]),'QUANTIDADE_KG':([25,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'comandos':([0,],[2,]),'comando':([0,2,],[3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> comandos','program',1,'p_program','churralang_parser.py',9),
  ('comandos -> comandos comando','comandos',2,'p_comandos','churralang_parser.py',24),
  ('comandos -> comando','comandos',1,'p_comandos','churralang_parser.py',25),
  ('comando -> AMIGO STRING CONTRIBUI NUMERO','comando',4,'p_comando_amigo_normal','churralang_parser.py',29),
  ('comando -> AMIGO STRING CONTRIBUI NUMERO VEGETARIANO','comando',5,'p_comando_amigo_veg','churralang_parser.py',37),
  ('comando -> ITEM CARNE STRING PRECO_KG NUMERO QUANTIDADE_KG NUMERO','comando',7,'p_comando_item_carne','churralang_parser.py',45),
  ('comando -> ITEM BEBIDA PRECO_L NUMERO QUANTIDADE_L NUMERO','comando',6,'p_comando_item_bebida','churralang_parser.py',55),
  ('comando -> ITEM COMIDA PRECO_UNIT NUMERO QUANTIDADE NUMERO','comando',6,'p_comando_item_comida','churralang_parser.py',60),
  ('comando -> ITEM ENTRETENIMENTO PRECO_UNIT NUMERO QUANTIDADE NUMERO','comando',6,'p_comando_item_entretenimento','churralang_parser.py',65),
  ('comando -> RATEIO IGUAL','comando',2,'p_comando_rateio','churralang_parser.py',70),
]
